name: Richard
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54827
title: The Teaser by Richard Giesemann
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eee2d2'
    - '#9ca3b3'
    - '#154b67'
    - '#436277'
    - '#030c11'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.6055000636260957
  rhythmicContrast: 0.5
purpose: []
